"""Python → Machine Learning → Survival Analysis: a complete interactive course.

Run with:  streamlit run app.py
"""

import streamlit as st

# Redirects pycox/torchtuples scratch files to the temp dir. Without this,
# their import-time writes crash every Section 6/7 page on Streamlit Cloud,
# where the repo mount and site-packages are read-only.
from utils import compat  # noqa: F401

st.set_page_config(
    page_title="Python → ML Course",
    page_icon="🎓",
    layout="wide",
)

pages = {
    "Start Here": [
        st.Page("sections/home.py", title="Welcome & How to Use", icon="🏠",
                default=True),
    ],
    "1 · Python Fundamentals": [
        st.Page("sections/section1_python/p1_data_structures.py",
                title="Data Structures & Comprehensions", icon="📦"),
        st.Page("sections/section1_python/p2_functions.py",
                title="Functions, args/kwargs & Lambdas", icon="🔧"),
        st.Page("sections/section1_python/p3_oop.py",
                title="Object-Oriented Programming", icon="🏗️"),
        st.Page("sections/section1_python/p4_error_handling.py",
                title="Error Handling", icon="🚨"),
        st.Page("sections/section1_python/p5_file_io.py",
                title="File I/O", icon="📄"),
        st.Page("sections/section1_python/p6_numpy.py",
                title="NumPy: Arrays & Broadcasting", icon="🔢"),
        st.Page("sections/section1_python/p7_pandas.py",
                title="Pandas: DataFrames", icon="🐼"),
        st.Page("sections/section1_python/p8_plotting.py",
                title="Plotting Fundamentals", icon="📊"),
    ],
    "2 · ML Foundations": [
        st.Page("sections/section2_ml_foundations/m1_what_is_ml.py",
                title="What Machine Learning Is", icon="🤖"),
        st.Page("sections/section2_ml_foundations/m2_loss_functions.py",
                title="Loss Functions", icon="📉"),
        st.Page("sections/section2_ml_foundations/m3_gradient_descent.py",
                title="Gradient Descent", icon="⛰️"),
        st.Page("sections/section2_ml_foundations/m4_splits.py",
                title="Train/Validation/Test Splits", icon="✂️"),
        st.Page("sections/section2_ml_foundations/m5_overfitting.py",
                title="Overfitting vs Underfitting", icon="🎭"),
        st.Page("sections/section2_ml_foundations/m6_regularization.py",
                title="L2 / Ridge Regularization", icon="🪢"),
        st.Page("sections/section2_ml_foundations/m7_hyperparameters.py",
                title="Parameters vs Hyperparameters", icon="🎛️"),
    ],
    "3 · Classical ML Algorithms": [
        st.Page("sections/section3_classical_ml/c1_knn.py",
                title="K-Nearest Neighbors", icon="🏘️"),
        st.Page("sections/section3_classical_ml/c2_trees.py",
                title="Decision Trees", icon="🌳"),
        st.Page("sections/section3_classical_ml/c3_svm.py",
                title="Support Vector Machines", icon="🛣️"),
        st.Page("sections/section3_classical_ml/c4_naive_bayes.py",
                title="Naive Bayes", icon="🎲"),
        st.Page("sections/section3_classical_ml/c5_random_forest.py",
                title="Bagging & Random Forests", icon="🌲"),
        st.Page("sections/section3_classical_ml/c6_boosting.py",
                title="Boosting (AdaBoost & GBM)", icon="🚀"),
        st.Page("sections/section3_classical_ml/c7_clustering.py",
                title="K-Means & Hierarchical", icon="🧲"),
        st.Page("sections/section3_classical_ml/c8_pca.py",
                title="PCA", icon="🧭"),
        st.Page("sections/section3_classical_ml/c9_feature_engineering.py",
                title="Feature Engineering", icon="🛠️"),
        st.Page("sections/section3_classical_ml/c10_evaluation.py",
                title="Model Evaluation & AIC", icon="📏"),
    ],
    "4 · PySpark & Big Data": [
        st.Page("sections/section4_pyspark/s1_why_spark.py",
                title="Why Spark Exists", icon="🔥"),
        st.Page("sections/section4_pyspark/s2_sparksession.py",
                title="SparkSession · RDDs vs DataFrames", icon="🎛️"),
        st.Page("sections/section4_pyspark/s3_lazy_evaluation.py",
                title="Lazy Evaluation & the Plan", icon="😴"),
        st.Page("sections/section4_pyspark/s4_dataframe_ops.py",
                title="Core DataFrame Operations", icon="🧱"),
        st.Page("sections/section4_pyspark/s5_spark_sql.py",
                title="Spark SQL", icon="🗄️"),
        st.Page("sections/section4_pyspark/s6_partitioning.py",
                title="Partitioning & Shuffles", icon="🧩"),
        st.Page("sections/section4_pyspark/s7_mllib.py",
                title="MLlib at Scale", icon="🤖"),
        st.Page("sections/section4_pyspark/s8_pandas_vs_spark.py",
                title="pandas vs PySpark", icon="⚖️"),
    ],
    "5 · Neural Networks": [
        st.Page("sections/section5_neural_networks/n1_single_neuron.py",
                title="Logistic Regression as a Neuron", icon="⚡"),
        st.Page("sections/section5_neural_networks/n2_activations.py",
                title="Activation Functions", icon="🎚️"),
        st.Page("sections/section5_neural_networks/n3_forward_pass.py",
                title="The Forward Pass", icon="➡️"),
        st.Page("sections/section5_neural_networks/n4_backprop.py",
                title="Backpropagation", icon="⬅️"),
        st.Page("sections/section5_neural_networks/n5_training_loop.py",
                title="The Training Loop", icon="🔁"),
        st.Page("sections/section5_neural_networks/n6_dropout_batchnorm.py",
                title="Dropout & Batch Norm", icon="🎛️"),
        st.Page("sections/section5_neural_networks/n7_cnn_rnn_landscape.py",
                title="CNNs, RNNs & Transformers", icon="🗺️"),
    ],
    "6 · DeepSurv (in full)": [
        st.Page("sections/section6_deepsurv/d1_survival_basics.py",
                title="Survival Analysis from Scratch", icon="⏳"),
        st.Page("sections/section6_deepsurv/d2_cox_model.py",
                title="The Cox PH Model", icon="📐"),
        st.Page("sections/section6_deepsurv/d3_faraggi_simon.py",
                title="Faraggi–Simon & Why It Failed", icon="🕰️"),
        st.Page("sections/section6_deepsurv/d4_architecture_loss.py",
                title="Architecture & Loss Function", icon="🧬"),
        st.Page("sections/section6_deepsurv/d5_training_techniques.py",
                title="Training Techniques", icon="🛠️"),
        st.Page("sections/section6_deepsurv/d6_recommender.py",
                title="The Treatment Recommender", icon="🔀"),
        st.Page("sections/section6_deepsurv/d7_simulation.py",
                title="The Paper's Experiment, Rebuilt", icon="🔬"),
        st.Page("sections/section6_deepsurv/d8_results_hyperparams.py",
                title="Results & Hyperparameter Search", icon="📊"),
    ],
    "7 · DeepHit (in full)": [
        st.Page("sections/section7_deephit/h1_why_ph_fails.py",
                title="Why Proportional Hazards Fails", icon="🏏"),
        st.Page("sections/section7_deephit/h2_features.py",
                title="Cricket Data & Feature Engineering", icon="🛠️"),
        st.Page("sections/section7_deephit/h3_discretising.py",
                title="Discretising Time into Bins", icon="🪓"),
        st.Page("sections/section7_deephit/h4_softmax_pmf.py",
                title="Softmax → a PMF over Bins", icon="🎯"),
        st.Page("sections/section7_deephit/h5_loss.py",
                title="The Two-Part Loss", icon="⚖️"),
        st.Page("sections/section7_deephit/h6_architecture.py",
                title="Architecture & Competing Risks", icon="🏗️"),
        st.Page("sections/section7_deephit/h7_head_to_head.py",
                title="DeepSurv vs DeepHitSingle", icon="🥊"),
    ],
}

pg = st.navigation(pages)
pg.run()
